- name: Update Packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Python
  apt:
    name: python3
    state: present

- name: Install Node.js y npm
  apt:
    name: 
      - nodejs
      - npm
    state: present

- name: Install pm2 globally
  npm:
    name: pm2@latest
    global: yes