version: 2.1
orbs:
  slack: circleci/slack@4.12.5

parameters:
  workflow_id:
    type: string
    default: '${CIRCLE_WORKFLOW_ID:0:7}'

commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      workflow_id:
        type: string
        default: '${CIRCLE_WORKFLOW_ID:0:7}'
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            echo "Destroying environment: << parameters.workflow_id >> "
            aws cloudformation delete-stack \
            --stack-name udapeople-backend-<<pipeline.parameters.workflow_id>>
            aws s3 rm s3://udapeople-<<pipeline.parameters.workflow_id>> --recursive
            aws cloudformation delete-stack \
            --stack-name udapeople-frontend-<<pipeline.parameters.workflow_id>>

  revert-migrations:
    description: Revert the last migration if successfully run in the current workflow.
    parameters:
      workflow_id:
        type: string   
        default: '${CIRCLE_WORKFLOW_ID:0:7}'   
    steps:
      - run:
          name: Revert migrations
          when: on_fail
          command: |
            cd ~/project/backend
            npm install
            npm run build
            npm run migrations:revert
            
jobs:
  build-frontend:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            # Your code here
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
      - slack/notify:
          channel: fail
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: success
          event: pass
          template: basic_success_1

  build-backend:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            # Your code here
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
      - slack/notify:
          channel: fail
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: success
          event: pass
          template: basic_success_1    

  test-frontend:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-test]
      - run:
          name: Front-end Test
          command: |
            cd frontend
            npm install
            npm run test
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-test
      - slack/notify:
          channel: fail
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: success
          event: pass
          template: basic_success_1
                
  test-backend:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys: [backend-test]
      - run:
          name: Back-end Test
          command: |
            cd backend
            npm install
            npm run test
      - save_cache:
          paths: [backend/node_modules]
          key: backend-test
      - slack/notify:
          channel: fail
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: success
          event: pass
          template: basic_success_1
            
  scan-frontend:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-scan]
      - run:
          name: Front-end Scan
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit fix --audit-level=critical --force
            ## if the "npm autit fix" command above could not fix all critical vulnerabilities, try "npm audit fix --force" again
            npm audit --audit-level=critical
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-scan
      - slack/notify:
          channel: fail
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: success
          event: pass
          template: basic_success_1

  scan-backend:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys: [backend-scan]
      - run:
          name: Back-end Scan
          command: |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit fix --audit-level=critical --force
            ## if the "npm autit fix" command above could not fix all critical vulnerabilities, try "npm audit fix --force" again
            npm audit --audit-level=critical
      - save_cache:
          paths: [backend/node_modules]
          key: backend-scan
      - slack/notify:
          channel: fail
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: success
          event: pass
          template: basic_success_1

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure back-end infrastructure exists
          environment:
            AWS_CLI_STR_ACCESS_KEY: $AWS_ACCESS_KEY_ID
            AWS_CLI_STR_PROFILE_NAME: $AWS_SECRET_ACCESS_KEY
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project=udapeople \
              --stack-name udapeople-backend-<<pipeline.parameters.workflow_id>>  \
              --region us-east-1 \
              --parameter-overrides ID=<<pipeline.parameters.workflow_id>> 
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project=udapeople \
              --region us-east-1 \
              --stack-name udapeople-frontend-<<pipeline.parameters.workflow_id>> \
              --parameter-overrides ID=<<pipeline.parameters.workflow_id>> 
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            public_ip=$(aws ec2 describe-instances \
            --filters "Name=tag:aws:cloudformation:stack-name, Values=udapeople-backend-<<pipeline.parameters.workflow_id>>" \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --region us-east-1)
            echo $public_ip >> .circleci/ansible/inventory.txt
            cat .circleci/ansible/inventory.txt
            yum install -y tar gzip
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/ansible/inventory.txt
      - destroy-environment:
          workflow_id: <<pipeline.parameters.workflow_id>> 
      - slack/notify:
          channel: fail
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: success
          event: pass
          template: basic_success_1   

  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.16
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - '82:66:86:8e:b3:67:f0:7c:fb:d4:31:85:81:2b:1e:d7:d6:8d:71:e3'
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
            cat .circleci/ansible/inventory.txt
      - run:
          name: Configure server
          command: |         
            echo $SSH_PEM
            echo ENVIRONMENT=production > "backend/.env"
            echo TYPEORM_CONNECTION=postgres >> "backend/.env"
            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"
            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
            echo NODE_ENV=production >> "backend/.env"
            echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
            echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
            echo TYPEORM_DRIVER_EXTRA=$TYPEORM_DRIVER_EXTRA >> "backend/.env"
            cat backend/.env

            cd .circleci/ansible 
            cat inventory.txt
            ansible-playbook -i inventory.txt configure-server.yml
      - persist_to_workspace:
          root: ~/
          paths:
            - "project/backend"
      - destroy-environment:
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
        
  run-migrations:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: |
            sudo apt install -y tar gzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -qq awscliv2.zip
            sudo ./aws/install
      - restore_cache:
          keys: [backend-build]
      - attach_workspace:
          at: ~/
      - run:
          name: Run migrations
          command: |
            cd backend
            sudo npm run migrations >> migrations.txt
            cat migrations.txt
      - run:
          name: Send migration results to kvdb.io
          command: |
            if grep -q "has been executed successfully." ~/project/backend/migrations.txt
            then
              # curl --insecure https://kvdb.io/UCp9EpWYWjhiJFv93ujtRp/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
              curl --insecure https://kvdb.io/UCp9EpWYWjhiJFv93ujtRp/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
            fi
      - destroy-environment:
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7} 
      # - slack/notify:
      #     channel: fail
      #     event: fail
      #     template: basic_fail_1
      # - slack/notify:
      #     channel: success
      #     event: pass
      #     template: basic_success_1    

  deploy-frontend:
    docker:
      - image: python:3.7-alpine3.16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update --no-cache tar gzip nodejs npm 
            apk add python3 py3-pip 
            pip3 install awscli --upgrade 
      - run:
          name: Get backend url
          environment:
            AWS_CLI_STR_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_CLI_STR_PROFILE_NAME: $AWS_SECRET_ACCESS_KEY
          command: |
            export public_ip=$(aws ec2 describe-instances \
            --filters "Name=tag:aws:cloudformation:stack-name,Values=udapeople-backend-<<pipeline.parameters.workflow_id>>" \
            --query "Reservations[0].Instances[0].PublicIpAddress")
            export API_URL="http://${public_ip}:3030"
            echo "API_URL = ${API_URL}"
            export API_URL=$(echo "http://${public_ip}:3030" | sed  's/"//g')
            echo ${API_URL} >> frontend/.env
            cat frontend/.env
      - run:
          name: Deploy frontend objects
          command: |
            cd frontend
            npm install 
            npm run build 
            tar -czvf artifact-"<<pipeline.parameters.workflow_id>>".tar.gz dist
            aws s3 cp dist s3://udapeople-<<pipeline.parameters.workflow_id>> --recursive
      - destroy-environment:
          workflow_id: <<pipeline.parameters.workflow_id>>
      - revert-migrations:
          workflow_id: <<pipeline.parameters.workflow_id>>
                    
  deploy-backend:
    docker:
      - image: python:3.7-alpine3.16
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '82:66:86:8e:b3:67:f0:7c:fb:d4:31:85:81:2b:1e:d7:d6:8d:71:e3'
      - run:
          name: Install dependencies
          command: |
            apk add --update --no-cache tar gzip nodejs npm aws-cli ansible
      - restore_cache:
          keys: [backend-build]
      - attach_workspace:
          at: ~/
      - run:
          name: Deploy backend
          command: |
            cd backend
            npm install
            npm run build
            cd ..
            tar -C backend -czvf artifact.tar.gz .
            mkdir -p ~/project/.circleci/ansible/roles/deploy/files/
            mv artifact.tar.gz .circleci/ansible/roles/deploy/files/artifact.tar.gz
            cd .circleci/ansible
            echo "Contents of the inventory.txt file is ------$(cat inventory.txt)"
            ansible-playbook -i inventory.txt deploy-backend.yml
      - destroy-environment:
          workflow_id: <<pipeline.parameters.workflow_id>>
      # - revert-migrations:
      #     workflow_id: <<pipeline.parameters.workflow_id>>

  smoke-test:
    docker:
      - image: python:3.7-alpine3.16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update --no-cache curl aws-cli nodejs npm
            apk add --update --no-cache tar gzip nodejs npm 
            apk add python3 py3-pip 
            pip3 install awscli --upgrade
      - run:
          name: Backend smoke test.
          command: |
            export BACKEND_IP=$(aws ec2 describe-instances \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --filters Name=tag:aws:cloudformation:stack-name,Values=udapeople-backend-<<pipeline.parameters.workflow_id>>)
            export API_URL=$(echo "http://${BACKEND_IP}:3030" | sed  's/"//g')
            echo  $API_URL
            if curl --connect-timeout 5 "${API_URL}/api/status" | grep "ok"; then return 0; else return 1; fi
      - run:
          name: Frontend smoke test.
          command: |
            export URL="http://udapeople-<<pipeline.parameters.workflow_id>>.s3.${AWS_DEFAULT_REGION}.amazonaws.com/index.html#/employees"            
            echo $URL
            if curl ${URL} | grep "Welcome"; then return 0; else return 1; fi
      - destroy-environment:
          workflow_id: <<pipeline.parameters.workflow_id>>
      - revert-migrations:
          workflow_id: <<pipeline.parameters.workflow_id>>  

  cloudfront-update:
    docker:
        - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt install -y tar gzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -qq awscliv2.zip
            sudo ./aws/install
      - run:
          name: Update cloudfront distribution
          command: |
            export OldWorkflowID=$(aws cloudformation list-exports \
            --query "Exports[?Name==\`ID\`].Value" \
            --no-paginate --output text)
            aws cloudformation deploy \
            --template-file .circleci/files/cloudfront.yml \
            --region us-east-1 \
            --stack-name InitialStack \
            --parameter-overrides WorkflowID="udapeople-<<pipeline.parameters.workflow_id>> " \
            --tags project=udapeople
      - destroy-environment:
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
      - revert-migrations:
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}

  cleanup:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Get old stack workflow id and remove stacks
          command: |
            echo <<pipeline.parameters.workflow_id>>
            export OldWorkflowID=<<pipeline.parameters.workflow_id>>
            export STACKS=$(aws cloudformation list-stacks \
            --query "StackSummaries[*].StackName" \
            --stack-status-filter CREATE_COMPLETE --no-paginate --output text)
            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
            then
              echo "----------cleaning up stacks------------"
              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
            fi

  add-prometheus-node-exporter:
    docker:
      - image: python:3.7-alpine3.16
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '62:42:d3:b3:b9:88:b4:9d:63:c9:84:6c:82:28:10:70:38:6b:da:8e'
      - run:
          name: Install dependencies
          command: |
            apk add --update aws-cli tar gzip ansible nodejs npm
      - attach_workspace:
          at: ~/
      - run:
          name: Setup Prometheus Node Exporter
          command: |
            cd .circleci/ansible
            cat inventory.txt
            ansible-playbook -i inventory.txt node-exporter.yml
      - destroy-environment:
          workflow_id: <<pipeline.parameters.workflow_id>>
      - revert-migrations:
          workflow_id: <<pipeline.parameters.workflow_id>>
            

workflows:
  default:
    jobs:
      - build-frontend:
          context: slack-secrets
      - build-backend:
          context: slack-secrets
      - test-frontend:
          requires: [build-frontend]
          context: slack-secrets
      - test-backend:
          requires: [build-backend]
          context: slack-secrets
      - scan-backend:
          requires: [build-backend]
          context: slack-secrets
      - scan-frontend:
          requires: [build-frontend]
          context: slack-secrets
      - deploy-infrastructure:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
          filters:
            branches:
              only: [main]
          context: slack-secrets
      - configure-infrastructure:
          requires: [deploy-infrastructure]
          filters:
            branches:
              only: [main]
      - run-migrations:
          requires: [configure-infrastructure]
          filters:
            branches:
              only: [main]
      - deploy-frontend:
          requires: [run-migrations]
          filters:
            branches:
              only: [main]
      - deploy-backend:
          requires: [run-migrations]
          filters:
            branches:
              only: [main]
      - smoke-test:
          requires: [deploy-backend, deploy-frontend]
          filters:
            branches:
              only: [main]
      - cloudfront-update:
          requires: [smoke-test]
          filters:
            branches:
              only: [main]
      - add-prometheus-node-exporter:
          requires: [deploy-infrastructure]
      # - cleanup:
      #     requires: [cloudfront-update]